gateways:
  api:
    namespace: istio-system
    additionalLabels: {}
    additionalAnnotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    spec:
      gatewayClassName: istio
      listeners:
      - allowedRoutes:
          namespaces:
            from: All
        hostname: "*.example.com"
        name: apipassthrough
        port: 443
        protocol: TLS
        tls:
          mode: Passthrough