gateways:
  internal:
    namespace: istio-system
    additionalLabels: {}
    additionalAnnotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    spec:
      gatewayClassName: istio
      listeners:
      - protocol: HTTP
        port: 80
        name: http
        hostname: "*.internal.example.com"
        allowedRoutes:
          namespaces:
            from: All
      - protocol: HTTPS
        hostname: "*.internal.example.com"
        port: 443
        name: https
        tls:
          mode: Terminate
          certificateRefs:
            - name: app.example-com-tls
              kind: Secret
              namespace: istio-system
        allowedRoutes:
          namespaces:
            from: All
